### PR TITLE
Support localization

### PR DESCRIPTION
**Pull request by Idomo**
Added `NSLocalizedString()` when setting the text of the `placeholderTextView`.

### CODE REVIEW

**Comment by devxoul** [comment]
Why not just using:

```objc
textView.placeholder = NSLocalizedString(@"My placeholder", @"");
```

**Comment by devxoul** [comment]
I mean, why do the text view translate the placeholder text?

**Comment by Idomo** [comment]
@devxoul Sorry, I didn't understand what you said, the change I added is like this in swift:
`NSLocalizedString(placeholder, comment: "\(placeholder) placeholder")`
Just add comment that indicate this text is the text from the placeholder.

**Comment by Idomo** [comment]
@devxoul I couldn't find `textView.placeholder`, I'v putted the code in the method that set the text, I didn't understand what the problem there.

**Comment by Idomo** [comment]
Oh, I did it because I'm using the `IBDesginable` and this is the only way to call `NSLocalizedString` from there.

**Comment by devxoul** [comment]
Users can set **translated** placeholder text if they want. UITextView should not translate the given placeholder.

**Comment by devxoul** [comment]
Because it is implicit and unpredictable. `UITextField` doesn't work like that. I'd like to keep the behavior as same as the `UITextField`'s placeholder. Imagine if the user doesn't want to translate the text when there is a same localizable string. For example:

**Localizable.strings**

```strings
"OK" = "확인";
```

**MyView.swift**

```swift
self.textView.placeholder = "OK" // I'd like to display 'OK' but it will translate to '확인'.
```

**Comment by Idomo** [comment]
@devxoul Humm I understood now, thanks :)

**Pull request closed without merging**
