### PR TITLE
add placeholderFont to fixed attributedPlaceholder font overrided

### PR DESCRIPTION
**Pull request by aelam**

### CODE REVIEW

**Comment by aelam** [comment]
see #20

**Comment by devxoul** [comment]
@aelam, Thanks for your work.

However, I cannot merge your PR because:

1. I'm trying to make UITextView+Placeholder to follow the behaviors of the placeholder of UITextField. UITextField does not have `placeholderFont` property.
2. There's too many unnecessary file diffs.

Thanks.

**Comment by aelam** [comment]
try UITextView.

**Comment by devxoul** [comment]
It has been fixed in #27. Thank you for waiting, guys!

**Pull request closed without merging**
